server:
  port: 8080


spring:
  rabbitmq:
      host: 192.168.20.168
      #host: 192.168.124.7
      port: 5672
      username: sang
      password: 123
       #设置手动ack回执
      listener:
        simple:
          acknowledge-mode: manual    #none 不确认，auto 自动确认 manual 手动确认
          

